* Setting up on host
  Install
  Add to groups?
  -> could just run as sudo instead: http://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/
  $ sudo systemctl start docker (could also enable it)
* Installing a box
  Should happen by default by $ docker run <box>, or by Dockerfile
  Check out boxes at DockerHub
  $ docker pull ubuntu:16.04 (or something of the sort to get a specific image)
* Setting up Dockerfile
  FROM ubuntu:16.04
  -> will download this image
  Use RUN to set up box
  CMD is the default command to run in the image. Only one is allowed in Dockerfile
* Building an image
  $ sudo docker build -t <tag> . (assuming there is a dockerfile in the current directory)
* Seeing existing images
  $ sudo docker images
* Seeing existing containers
  $ sudo docker ps -a
* Removing images and containers
  $ docker rmi <image>
  $ docker rm <container>
* Turn container into image
  $ sudo docker commit <container id> <image name>
* To get bash working
  $ sudo docker run -i -t <image name> /bin/bash
  -i makes it interactive
  -t allocates a pseudo TTY
* Running compilation
** Mounting host director as data volume
   $ docker run -d -P --name web -v /src/webapp:/opt/webapp training/webapp python app.py
   -d flag tells docker to run container in background
   -P flag tells Docker to map any required network ports inside our container to our host
   -v flag adds data volume

   So generally:
   $ docker run -d -P --name <name of container> -v <host absolute path>:<container absolute path>\
     <image name> <thing to do>
   Might not need -P flag in all cases, though.
   Might work well with pyret and cpo!
** Progress
   sudo docker run --name compilation -v /home/preston/docker-experiment:/opt/docker-experiment\
   ubuntu-gcc gcc test.c
   -> can't find test.c

   can add --rm flag to immediately destroy container
** Final command
   $ sudo docker run --rm -v /home/preston/docker-experiment:/opt/src ugcc gcc test.c
   and a.out is in current directory!
* To think about:
  - Having one container compile and another container run: http://blog.terranillius.com/post/docker_builder_pattern/
  - Add preston to docker user group so that I don't have to supply password when running make in emacs.
